// Sprite URLs are resolved through Vite (import.meta.glob) so they load in dev,
// build, and PWA precache without hardcoding hashed paths. Files live in
// /assets/sprites/ (project root), generated by tools/process_sprites.py.
const URLS = import.meta.glob('/assets/sprites/*.{png,jpg}', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

// Resolve by base name so a sprite can be .png or .jpg (background ships as JPEG).
const BY_NAME: Record<string, string> = {}
for (const [path, url] of Object.entries(URLS)) {
  const base = path.split('/').pop()!.replace(/\.(png|jpg)$/, '')
  BY_NAME[base] = url
}

const NAMES = [
  'player-ship', 'ufo', 'background',
  'shot-player', 'shot-enemy', 'shot-boss',
  'enemy-01', 'enemy-02', 'enemy-03', 'enemy-04',
  'boss-01', 'boss-02', 'boss-03', 'boss-04', 'boss-05',
  'powerup-rapid', 'powerup-spread', 'powerup-shield', 'powerup-life',
] as const

export const REQUIRED: string[] = [...NAMES]

export const SPRITES: Record<string, string> = Object.fromEntries(
  NAMES.map((n) => [n, BY_NAME[n]]),
)

export function placeholder(w: number, h: number, color: string): HTMLCanvasElement {
  const c = document.createElement('canvas'); c.width = w; c.height = h
  const x = c.getContext('2d')!
  x.fillStyle = color; x.fillRect(0, 0, w, h)
  x.strokeStyle = '#ffffff'; x.strokeRect(1, 1, w - 2, h - 2)
  return c
}

export function loadSprites(): Promise<Map<string, CanvasImageSource>> {
  const out = new Map<string, CanvasImageSource>()
  const jobs = NAMES.map((name) => new Promise<void>((res) => {
    const src = SPRITES[name]
    if (!src) { out.set(name, placeholder(48, 48, '#ff00ff')); return res() }
    const img = new Image()
    img.onload = () => { out.set(name, img); res() }
    img.onerror = () => { out.set(name, placeholder(48, 48, '#ff00ff')); res() }
    img.src = src
  }))
  return Promise.all(jobs).then(() => out)
}
